// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://yujqnnklrgnqywcvjkdy.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1anFubmtscmducXl3Y3Zqa2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE2NzQ2OTYsImV4cCI6MjA0NzI1MDY5Nn0.M6jTAcbl7jXEgFWvOW4ytmakgUyz_RkwJNQ8TEacUEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);